version: '3'
services:
  db:
     image: mysql:5.7
     restart: always
     container_name: mysql-container
     environment: 
       MYSQL_ROOT_PASSWORD: mypassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpressuser
       MYSQL_PASSWORD: wordpress
     volumes:
       - mysql_data:/var/lib/mysql
     networks:
      - wordpress_network
     ports:
       - "3306:3306"
   #wordpress services:
  wordpress: 
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpressuser
       WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    ports:
      - "8080:80"
volumes:
  mysql_data:
  wordpress_data:
networks:
   wordpress_network:
     driver: bridge


