version: '3'
services: 
  node-app:
    build:
      context: .
    ports:
      - "8000:4000"
    depends_on:
      - mongo
    image: wahaduzzaman/custom_nodeapp:01
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"